### ISSUE TITLE
Что значит "Присоединяйтесь к нам"?

### ISSUE THREAD

**Issue by N1qro** [QBoff/NFT-Market-Offense#13]
На домашней странице в самом низу есть секция "**Присоединяйтесь к нам**" с кнопкой "**Подписаться**".
Это опять очередная приукрашенная кнопка регистрации или что? Для чего она нужна? Нужны объяснения, @QBoff.

**Comment by mello-bit** [comment]
Это перенапряжение на регистрацию

**Comment by N1qro** [comment]
Why, зачем она? Их и так сколько? 3 уже

**Comment by mello-bit** [comment]
Могу удалить, да, лучше я это уберу

**Comment by mello-bit** [comment]
Я убрал, можешь закрывать вопрос
