### ISSUE TITLE
Секция популярных NFT

### ISSUE THREAD

**Issue by N1qro** [QBoff/NFT-Market-Offense#6]
Не совсем понятно, исходя из чего NFT может считаться популярным и отображаться на главной странице. Нужно выяснить, добавить специальные метрики и добавить их динамическое отображение. Каждый раз видеть только 3 одинаковых картинки скучно.

Жду метрик, бд подредачу.

**Comment by mello-bit** [comment]
По количеству продаж, у каждой nft будет ее количество продаж
